basic:
  seed: 42
  n_envs: 24
  n_steps: 360
  step_count: 100000000 # 100M
  resume: True
  pretrained_path: ./models/best_model.zip

callbacks:  
  eval:
    best_model_save_path: './models/'
    # log_path: './models/'
    eval_freq: 720  # Run it every 2 training iterations
    n_eval_episodes: 5  # Run 5 games
    deterministic: False
    render: False

  checkpoints:
    save_freq: 50000  # 1,200,000
    save_path: './models/'
    name_prefix: 'rl_model'
    verbose: 0

  selfplay:
    model_type: "latest"  # "best" or "latest"
    load_freq_rollout: 50  # 1 rollout â‰ˆ 24576 steps

model:
    verbose: 0
    tensorboard_log: "./tensorboard/"
    learning_rate: 0.001
    gamma: 0.998
    gae_lambda: 0.95
    batch_size: 1024
    n_steps: 1024